openapi: 3.0.0
info:
  title: Authentication API
  description: Authenticate a user
  version: 1.0.0
paths:
  /register:
    post:
      summary: Create account
      tags:
        - POST
      operationId: registerCustomer
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customerInput'
      responses:
        '200':
          description: Customer registered successfully
  /login:
    post:
      summary: Login in system
      tags:
        - POST
      operationId: authenticate
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authentication'
      responses:
        '200':
          description: Logged successful
components:
  schemas:
    customerInput:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required:
        - email
        - password
        - firstName
        - lastName
    authentication:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password