version: '3'
services:
  gateway:
    build: ./zuul-gateway
    ports:
      - "80:9000"
    environment:
      GATEWAY_PORT: 9000
      EUREKA_URL: "http://discovery-service:8761/eureka/"
      FRONTEND_URL: "http://frontend"
    networks:
      - internal
  frontend:
    build: ./frontend
    ports:
      - "9000:80"
    networks:
      - internal
  authentication:
    build: ./authentication
    environment:
      EUREKA_URL: "http://discovery-service:8761/eureka/"
      DB_HOST: authentication-db
      DB_PORT: 5432
      DB_USERNAME: authentication
      DB_PASSWORD: CzgjDw7V&Xd2d*
      DB_NAME: authentication
    networks:
      - internal
    depends_on:
      - authentication-db
  authentication-db:
    image: postgres
    environment:
      POSTGRES_USER: authentication
      POSTGRES_PASSWORD: CzgjDw7V&Xd2d*
      POSTGRES_DB: authentication
    volumes:
      - /var/lib/authentication-db:/var/lib/postgresql/data
    networks:
      - internal
  card:
    build: ./card
    environment:
      EUREKA_URL: "http://discovery-service:8761/eureka/"
      DB_HOST: card-db
      DB_PORT: 5432
      DB_USERNAME: card
      DB_PASSWORD: C44na&7kou8kF#
      DB_NAME: card
    networks:
      - internal
    depends_on:
      - card-db
  card-db:
    image: postgres
    environment:
      POSTGRES_USER: card
      POSTGRES_PASSWORD: C44na&7kou8kF#
      POSTGRES_DB: card
    volumes:
      - /var/lib/card-db:/var/lib/postgresql/data
    networks:
      - internal
  customer-profile:
    build: ./customer-profile
    environment:
      EUREKA_URL: "http://discovery-service:8761/eureka/"
    networks:
      - internal
  transaction:
    build: ./transaction
    environment:
      EUREKA_URL: "http://discovery-service:8761/eureka/"
    networks:
      - internal
  discovery-service:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_PORT: 8761
    networks:
      - internal

networks:
  internal:
    driver: bridge
