openapi: 3.0.0
info:
  title: Register API
  description: Register API for register new customer
  version: 1.0.0
paths:
  /register:
    post:
      summary: Create account
      tags:
        - POST
      operationId: registerCustomer
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customerInput'
      responses:
        '200':
          description: Customer registered successfully
  /edit:
    put:
      summary: Editing customer profile
      tags:
        - PUT
      operationId: editProfile
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customerInput'
      responses:
        '200':
          description: Customer profile successfully edited

components:
  responses:
    Ok:
      description: Ok
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/customerInput'
  schemas:
    customerInput:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required:
        - email
        - password
        - firstName
        - lastName