openapi: 3.0.0
info:
  title: Card system API
  description: Create, delete card and add money
  version: 1.0.0
paths:
  /create:
    post:
      summary: Create a new card
      tags:
        - POST
      operationId: createCard
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/card'
      responses:
        '200':
          description: Card was created
  /delete/{cardId}:
    get:
      summary: Delete card
      tags:
        - GET
      operationId: deleteCard
      parameters:
        - in: path
          name: cardId
          required: True
          description: Id of card
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Card was deleted
  /addMoney:
    put:
      summary: Add money on card
      tags:
        - PUT
      operationId: addMoney
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payment'
      responses:
        '200':
          description: Money was added
components:
  responses:
    Ok:
      description: Ok
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/payment'
  schemas:
    card:
      type: object
      properties:
        cardId:
          type: string
        userId:
          type: string
        balance:
          type: integer
      required:
        - cardId
        - userId
        - balance
    payment:
      type: object
      properties:
        cardId:
          type: string
        amount:
          type: integer
      required:
        - cardId
        - amount