openapi: 3.0.0
info:
  title: Account system API
  description: Create, delete account and add money
  version: 1.0.0
paths:
  /create:
    post:
      summary: Create a new account
      tags:
        - POST
      operationId: createAccount
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/account'
      responses:
        '200':
          description: Account was created
  /delete/{accountId}:
    get:
      summary: Delete account
      tags:
        - GET
      operationId: deleteAccount
      parameters:
        - in: path
          name: accountId
          required: True
          description: Id of account
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Account was deleted
  /addMoney:
    put:
      summary: Add money to account
      tags:
        - PUT
      operationId: addMoney
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payment'
      responses:
        '200':
          description: Money was added
components:
  responses:
    Ok:
      description: Ok
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/account'
  schemas:
    account:
      type: object
      properties:
        accountId:
          type: string
        userId:
          type: string
        balance:
          type: integer
      required:
        - accountId
        - userId
        - balance
    payment:
      type: object
      properties:
        accountId:
          type: string
        amount:
          type: integer
      required:
        - accountId
        - amount